# Generated by Django 3.1.1 on 2020-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='funds',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
